// Code generated by Kitex v0.15.2. DO NOT EDIT.

package kitex_gen

import (
	"context"

	"github.com/cloudwego/prutal"
)

// CheckUserOnlineReq 检查用户在线状态请求
type CheckUserOnlineReq struct {
	UserIDs []string `protobuf:"bytes,1,rep,name=userIDs" json:"userIDs,omitempty"` // 用户ID列表
}

func (x *CheckUserOnlineReq) Reset() { *x = CheckUserOnlineReq{} }

func (x *CheckUserOnlineReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CheckUserOnlineReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckUserOnlineReq) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

// UserOnlineStatus 用户在线状态
type UserOnlineStatus struct {
	UserID          string  `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`                    // 用户ID
	IsOnline        bool    `protobuf:"varint,2,opt,name=isOnline" json:"isOnline,omitempty"`               // 是否在线
	ConnectionCount int32   `protobuf:"varint,3,opt,name=connectionCount" json:"connectionCount,omitempty"` // 连接数量
	PlatformIDs     []int32 `protobuf:"varint,4,rep,packed,name=platformIDs" json:"platformIDs,omitempty"`  // 在线平台ID列表
	LastActiveTime  int64   `protobuf:"varint,5,opt,name=lastActiveTime" json:"lastActiveTime,omitempty"`   // 最后活跃时间戳
}

func (x *UserOnlineStatus) Reset() { *x = UserOnlineStatus{} }

func (x *UserOnlineStatus) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserOnlineStatus) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserOnlineStatus) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserOnlineStatus) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *UserOnlineStatus) GetConnectionCount() int32 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

func (x *UserOnlineStatus) GetPlatformIDs() []int32 {
	if x != nil {
		return x.PlatformIDs
	}
	return nil
}

func (x *UserOnlineStatus) GetLastActiveTime() int64 {
	if x != nil {
		return x.LastActiveTime
	}
	return 0
}

// CheckUserOnlineResp 检查用户在线状态响应
type CheckUserOnlineResp struct {
	Statuses []*UserOnlineStatus `protobuf:"bytes,1,rep,name=statuses" json:"statuses,omitempty"` // 用户在线状态列表
}

func (x *CheckUserOnlineResp) Reset() { *x = CheckUserOnlineResp{} }

func (x *CheckUserOnlineResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CheckUserOnlineResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckUserOnlineResp) GetStatuses() []*UserOnlineStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

// PushMessage 推送消息结构（参考Message结构，加上元数据）
type PushMessage struct {
	RequestID string            `protobuf:"bytes,1,opt,name=requestID" json:"requestID,omitempty"`                                                                         // 请求ID（用于请求-响应匹配）
	Type      string            `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`                                                                                   // 消息类型（如：push, notification, command等）
	Service   string            `protobuf:"bytes,3,opt,name=service" json:"service,omitempty"`                                                                             // 目标服务名称（可选）
	Method    string            `protobuf:"bytes,4,opt,name=method" json:"method,omitempty"`                                                                               // 服务方法名称（可选）
	Payload   []byte            `protobuf:"bytes,5,opt,name=payload" json:"payload,omitempty"`                                                                             // 消息有效载荷/数据（字节数组）
	Error     string            `protobuf:"bytes,6,opt,name=error" json:"error,omitempty"`                                                                                 // 错误信息（响应时使用，可选）
	Timestamp int64             `protobuf:"varint,7,opt,name=timestamp" json:"timestamp,omitempty"`                                                                        // 时间戳
	Metadata  map[string]string `protobuf:"bytes,8,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据（可选，用于传递额外的键值对信息，如：消息优先级、过期时间、路由信息等）
}

func (x *PushMessage) Reset() { *x = PushMessage{} }

func (x *PushMessage) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PushMessage) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PushMessage) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *PushMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PushMessage) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *PushMessage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PushMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PushMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PushMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PushMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// PushDataReq 推送数据请求
type PushDataReq struct {
	UserIDs   []string     `protobuf:"bytes,1,rep,name=userIDs" json:"userIDs,omitempty"`      // 目标用户ID列表
	Message   *PushMessage `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`      // 推送的消息内容
	Broadcast bool         `protobuf:"varint,3,opt,name=broadcast" json:"broadcast,omitempty"` // 是否广播给所有连接（如果为true，忽略userIDs）
}

func (x *PushDataReq) Reset() { *x = PushDataReq{} }

func (x *PushDataReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PushDataReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PushDataReq) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

func (x *PushDataReq) GetMessage() *PushMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PushDataReq) GetBroadcast() bool {
	if x != nil {
		return x.Broadcast
	}
	return false
}

// PushResult 推送结果
type PushResult struct {
	UserID          string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`                    // 用户ID
	Success         bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`                 // 是否成功
	Error           string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`                      // 错误信息（如果失败）
	ConnectionCount int32  `protobuf:"varint,4,opt,name=connectionCount" json:"connectionCount,omitempty"` // 推送到的连接数量
}

func (x *PushResult) Reset() { *x = PushResult{} }

func (x *PushResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PushResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PushResult) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *PushResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PushResult) GetConnectionCount() int32 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

// PushDataResp 推送数据响应
type PushDataResp struct {
	SuccessCount int32         `protobuf:"varint,1,opt,name=successCount" json:"successCount,omitempty"` // 成功推送数量
	FailCount    int32         `protobuf:"varint,2,opt,name=failCount" json:"failCount,omitempty"`       // 失败推送数量
	Results      []*PushResult `protobuf:"bytes,3,rep,name=results" json:"results,omitempty"`            // 推送结果详情
}

func (x *PushDataResp) Reset() { *x = PushDataResp{} }

func (x *PushDataResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PushDataResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PushDataResp) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *PushDataResp) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *PushDataResp) GetResults() []*PushResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// PushToConnectionReq 推送到指定连接请求
type PushToConnectionReq struct {
	ConnectionID string       `protobuf:"bytes,1,opt,name=connectionID" json:"connectionID,omitempty"` // 连接ID
	Message      *PushMessage `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`           // 推送的消息内容
}

func (x *PushToConnectionReq) Reset() { *x = PushToConnectionReq{} }

func (x *PushToConnectionReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PushToConnectionReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PushToConnectionReq) GetConnectionID() string {
	if x != nil {
		return x.ConnectionID
	}
	return ""
}

func (x *PushToConnectionReq) GetMessage() *PushMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// PushToConnectionResp 推送到指定连接响应
type PushToConnectionResp struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"` // 是否成功
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`      // 错误信息（如果失败）
}

func (x *PushToConnectionResp) Reset() { *x = PushToConnectionResp{} }

func (x *PushToConnectionResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PushToConnectionResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PushToConnectionResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushToConnectionResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RegisterServiceReq 注册服务请求
// 网关转发流程：接收到客户端请求(service, method) -> 检查是否注册 -> 从注册中心获取服务实例 -> 转发数据
// 注意：ip:port 信息在注册中心中，这里只注册 service 和 method 的映射关系
type RegisterServiceReq struct {
	Service string   `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"` // 服务名称（必须在注册中心已注册）
	Methods []string `protobuf:"bytes,2,rep,name=methods" json:"methods,omitempty"` // 支持的方法列表（可选，如果为空则所有method都转发到此服务）
}

func (x *RegisterServiceReq) Reset() { *x = RegisterServiceReq{} }

func (x *RegisterServiceReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterServiceReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterServiceReq) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RegisterServiceReq) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

// RegisterServiceResp 注册服务响应
type RegisterServiceResp struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"` // 是否成功
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`      // 错误信息（如果失败）
}

func (x *RegisterServiceResp) Reset() { *x = RegisterServiceResp{} }

func (x *RegisterServiceResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterServiceResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterServiceResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterServiceResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// UnregisterServiceReq 注销服务请求
type UnregisterServiceReq struct {
	Service string   `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"` // 服务名称
	Methods []string `protobuf:"bytes,2,rep,name=methods" json:"methods,omitempty"` // 要注销的方法列表（可选，如果为空则注销该服务的所有方法）
}

func (x *UnregisterServiceReq) Reset() { *x = UnregisterServiceReq{} }

func (x *UnregisterServiceReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UnregisterServiceReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnregisterServiceReq) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *UnregisterServiceReq) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

// UnregisterServiceResp 注销服务响应
type UnregisterServiceResp struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"` // 是否成功
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`      // 错误信息（如果失败）
}

func (x *UnregisterServiceResp) Reset() { *x = UnregisterServiceResp{} }

func (x *UnregisterServiceResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UnregisterServiceResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnregisterServiceResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterServiceResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetServiceReq 获取服务请求
// 用于查询(service, method)是否已注册，ip:port 从注册中心获取
type GetServiceReq struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"` // 服务名称
	Method  string `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`   // 方法名称（可选）
}

func (x *GetServiceReq) Reset() { *x = GetServiceReq{} }

func (x *GetServiceReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetServiceReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetServiceReq) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetServiceReq) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// GetServiceResp 获取服务响应
type GetServiceResp struct {
	Registered bool   `protobuf:"varint,1,opt,name=registered" json:"registered,omitempty"` // 是否已注册
	Service    string `protobuf:"bytes,2,opt,name=service" json:"service,omitempty"`        // 服务名称（如果已注册，用于从注册中心查询实例）
}

func (x *GetServiceResp) Reset() { *x = GetServiceResp{} }

func (x *GetServiceResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetServiceResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetServiceResp) GetRegistered() bool {
	if x != nil {
		return x.Registered
	}
	return false
}

func (x *GetServiceResp) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type BackbonService interface {
	CheckUserOnline(ctx context.Context, req *CheckUserOnlineReq) (res *CheckUserOnlineResp, err error)
	PushData(ctx context.Context, req *PushDataReq) (res *PushDataResp, err error)
	PushToConnection(ctx context.Context, req *PushToConnectionReq) (res *PushToConnectionResp, err error)
	RegisterService(ctx context.Context, req *RegisterServiceReq) (res *RegisterServiceResp, err error)
	UnregisterService(ctx context.Context, req *UnregisterServiceReq) (res *UnregisterServiceResp, err error)
	GetService(ctx context.Context, req *GetServiceReq) (res *GetServiceResp, err error)
}
