// Code generated by Kitex v0.15.2. DO NOT EDIT.

package kitex_gen

import (
	"context"

	"github.com/cloudwego/prutal"
)

// CallRequest 网关调用后端服务的请求
// 网关接收到客户端请求后，将请求转发给对应的后端服务
type CallRequest struct {
	RequestID    string            `protobuf:"bytes,1,opt,name=requestID" json:"requestID,omitempty"`                                                                         // 请求ID（用于请求-响应匹配）
	Type         string            `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`                                                                                   // 消息类型（与Message.type对齐）
	Service      string            `protobuf:"bytes,3,opt,name=service" json:"service,omitempty"`                                                                             // 服务名称（与Message.service对齐）
	Method       string            `protobuf:"bytes,4,opt,name=method" json:"method,omitempty"`                                                                               // 方法名称（与Message.method对齐）
	Payload      []byte            `protobuf:"bytes,5,opt,name=payload" json:"payload,omitempty"`                                                                             // 业务数据（字节数组，由业务方解析，与Message.payload对齐）
	Metadata     map[string]string `protobuf:"bytes,6,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据（验证信息如token、track_id等，与Message.metadata对齐）
	UserID       string            `protobuf:"bytes,7,opt,name=userID" json:"userID,omitempty"`                                                                               // 用户ID（从连接中获取，额外字段）
	ConnectionID string            `protobuf:"bytes,8,opt,name=connectionID" json:"connectionID,omitempty"`                                                                   // 连接ID（可选，额外字段）
	Timestamp    int64             `protobuf:"varint,9,opt,name=timestamp" json:"timestamp,omitempty"`                                                                        // 时间戳（与Message.timestamp对齐）
}

func (x *CallRequest) Reset() { *x = CallRequest{} }

func (x *CallRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CallRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CallRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *CallRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CallRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CallRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CallRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *CallRequest) GetConnectionID() string {
	if x != nil {
		return x.ConnectionID
	}
	return ""
}

func (x *CallRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// CallResponse 网关调用后端服务的响应
type CallResponse struct {
	RequestID string            `protobuf:"bytes,1,opt,name=requestID" json:"requestID,omitempty"`                                                                         // 请求ID（对应请求的requestID）
	Type      string            `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`                                                                                   // 消息类型（与Message.type对齐）
	Success   bool              `protobuf:"varint,3,opt,name=success" json:"success,omitempty"`                                                                            // 是否成功
	Payload   []byte            `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`                                                                             // 响应数据（字节数组，由业务方解析，与Message.payload对齐）
	Error     string            `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`                                                                                 // 错误信息（如果失败，与Message.error对齐）
	Metadata  map[string]string `protobuf:"bytes,6,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 响应元数据（可选，与Message.metadata对齐）
	Timestamp int64             `protobuf:"varint,7,opt,name=timestamp" json:"timestamp,omitempty"`                                                                        // 时间戳（与Message.timestamp对齐）
}

func (x *CallResponse) Reset() { *x = CallResponse{} }

func (x *CallResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CallResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CallResponse) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *CallResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CallResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CallResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CallResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type BackService interface {
	Call(ctx context.Context, req *CallRequest) (res *CallResponse, err error)
}
