// Code generated by Kitex v0.15.2. DO NOT EDIT.

package backbonservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	backbon "github.com/rhp-QE/roc-foundation-service/long_connection_service/kitex_gen/backbon"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CheckUserOnline(ctx context.Context, Req *backbon.CheckUserOnlineReq, callOptions ...callopt.Option) (r *backbon.CheckUserOnlineResp, err error)
	PushData(ctx context.Context, Req *backbon.PushDataReq, callOptions ...callopt.Option) (r *backbon.PushDataResp, err error)
	PushToConnection(ctx context.Context, Req *backbon.PushToConnectionReq, callOptions ...callopt.Option) (r *backbon.PushToConnectionResp, err error)
	RegisterService(ctx context.Context, Req *backbon.RegisterServiceReq, callOptions ...callopt.Option) (r *backbon.RegisterServiceResp, err error)
	UnregisterService(ctx context.Context, Req *backbon.UnregisterServiceReq, callOptions ...callopt.Option) (r *backbon.UnregisterServiceResp, err error)
	GetService(ctx context.Context, Req *backbon.GetServiceReq, callOptions ...callopt.Option) (r *backbon.GetServiceResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kBackbonServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kBackbonServiceClient struct {
	*kClient
}

func (p *kBackbonServiceClient) CheckUserOnline(ctx context.Context, Req *backbon.CheckUserOnlineReq, callOptions ...callopt.Option) (r *backbon.CheckUserOnlineResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckUserOnline(ctx, Req)
}

func (p *kBackbonServiceClient) PushData(ctx context.Context, Req *backbon.PushDataReq, callOptions ...callopt.Option) (r *backbon.PushDataResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PushData(ctx, Req)
}

func (p *kBackbonServiceClient) PushToConnection(ctx context.Context, Req *backbon.PushToConnectionReq, callOptions ...callopt.Option) (r *backbon.PushToConnectionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PushToConnection(ctx, Req)
}

func (p *kBackbonServiceClient) RegisterService(ctx context.Context, Req *backbon.RegisterServiceReq, callOptions ...callopt.Option) (r *backbon.RegisterServiceResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegisterService(ctx, Req)
}

func (p *kBackbonServiceClient) UnregisterService(ctx context.Context, Req *backbon.UnregisterServiceReq, callOptions ...callopt.Option) (r *backbon.UnregisterServiceResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnregisterService(ctx, Req)
}

func (p *kBackbonServiceClient) GetService(ctx context.Context, Req *backbon.GetServiceReq, callOptions ...callopt.Option) (r *backbon.GetServiceResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetService(ctx, Req)
}
