// Code generated by Kitex v0.15.2. DO NOT EDIT.
package backbonservice

import (
	server "github.com/cloudwego/kitex/server"
	backbon "github.com/rhp-QE/roc-foundation-service/long_connection_service/kitex_gen/backbon"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler backbon.BackbonService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler backbon.BackbonService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
