// Code generated by Kitex v0.15.2. DO NOT EDIT.

package backservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	back "github.com/rhp-QE/roc-foundation-service/long_connection_service/kitex_gen/back"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Call": kitex.NewMethodInfo(
		callHandler,
		newCallArgs,
		newCallResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	backServiceServiceInfo                = NewServiceInfo()
	backServiceServiceInfoForClient       = NewServiceInfoForClient()
	backServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return backServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return backServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return backServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "BackService"
	handlerType := (*back.BackService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "back",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func callHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(back.CallRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(back.BackService).Call(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CallArgs:
		success, err := handler.(back.BackService).Call(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CallResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCallArgs() interface{} {
	return &CallArgs{}
}

func newCallResult() interface{} {
	return &CallResult{}
}

type CallArgs struct {
	Req *back.CallRequest
}

func (p *CallArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CallArgs) Unmarshal(in []byte) error {
	msg := new(back.CallRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CallArgs_Req_DEFAULT *back.CallRequest

func (p *CallArgs) GetReq() *back.CallRequest {
	if !p.IsSetReq() {
		return CallArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CallArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CallArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CallResult struct {
	Success *back.CallResponse
}

var CallResult_Success_DEFAULT *back.CallResponse

func (p *CallResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CallResult) Unmarshal(in []byte) error {
	msg := new(back.CallResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CallResult) GetSuccess() *back.CallResponse {
	if !p.IsSetSuccess() {
		return CallResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CallResult) SetSuccess(x interface{}) {
	p.Success = x.(*back.CallResponse)
}

func (p *CallResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CallResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Call(ctx context.Context, Req *back.CallRequest) (r *back.CallResponse, err error) {
	var _args CallArgs
	_args.Req = Req
	var _result CallResult
	if err = p.c.Call(ctx, "Call", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
