// Code generated by Kitex v0.15.2. DO NOT EDIT.

package backbonservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	kitex_gen "github.com/rhp-QE/roc-foundation-service/long_connection_service/kitex_gen"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CheckUserOnline": kitex.NewMethodInfo(
		checkUserOnlineHandler,
		newCheckUserOnlineArgs,
		newCheckUserOnlineResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"PushData": kitex.NewMethodInfo(
		pushDataHandler,
		newPushDataArgs,
		newPushDataResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"PushToConnection": kitex.NewMethodInfo(
		pushToConnectionHandler,
		newPushToConnectionArgs,
		newPushToConnectionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RegisterService": kitex.NewMethodInfo(
		registerServiceHandler,
		newRegisterServiceArgs,
		newRegisterServiceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnregisterService": kitex.NewMethodInfo(
		unregisterServiceHandler,
		newUnregisterServiceArgs,
		newUnregisterServiceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetService": kitex.NewMethodInfo(
		getServiceHandler,
		newGetServiceArgs,
		newGetServiceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	backbonServiceServiceInfo                = NewServiceInfo()
	backbonServiceServiceInfoForClient       = NewServiceInfoForClient()
	backbonServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return backbonServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return backbonServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return backbonServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "BackbonService"
	handlerType := (*kitex_gen.BackbonService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "backbon",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func checkUserOnlineHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.CheckUserOnlineReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.BackbonService).CheckUserOnline(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CheckUserOnlineArgs:
		success, err := handler.(kitex_gen.BackbonService).CheckUserOnline(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CheckUserOnlineResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCheckUserOnlineArgs() interface{} {
	return &CheckUserOnlineArgs{}
}

func newCheckUserOnlineResult() interface{} {
	return &CheckUserOnlineResult{}
}

type CheckUserOnlineArgs struct {
	Req *kitex_gen.CheckUserOnlineReq
}

func (p *CheckUserOnlineArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CheckUserOnlineArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.CheckUserOnlineReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CheckUserOnlineArgs_Req_DEFAULT *kitex_gen.CheckUserOnlineReq

func (p *CheckUserOnlineArgs) GetReq() *kitex_gen.CheckUserOnlineReq {
	if !p.IsSetReq() {
		return CheckUserOnlineArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CheckUserOnlineArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CheckUserOnlineArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CheckUserOnlineResult struct {
	Success *kitex_gen.CheckUserOnlineResp
}

var CheckUserOnlineResult_Success_DEFAULT *kitex_gen.CheckUserOnlineResp

func (p *CheckUserOnlineResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CheckUserOnlineResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.CheckUserOnlineResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CheckUserOnlineResult) GetSuccess() *kitex_gen.CheckUserOnlineResp {
	if !p.IsSetSuccess() {
		return CheckUserOnlineResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CheckUserOnlineResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.CheckUserOnlineResp)
}

func (p *CheckUserOnlineResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CheckUserOnlineResult) GetResult() interface{} {
	return p.Success
}

func pushDataHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.PushDataReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.BackbonService).PushData(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *PushDataArgs:
		success, err := handler.(kitex_gen.BackbonService).PushData(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PushDataResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newPushDataArgs() interface{} {
	return &PushDataArgs{}
}

func newPushDataResult() interface{} {
	return &PushDataResult{}
}

type PushDataArgs struct {
	Req *kitex_gen.PushDataReq
}

func (p *PushDataArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *PushDataArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.PushDataReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PushDataArgs_Req_DEFAULT *kitex_gen.PushDataReq

func (p *PushDataArgs) GetReq() *kitex_gen.PushDataReq {
	if !p.IsSetReq() {
		return PushDataArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PushDataArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PushDataArgs) GetFirstArgument() interface{} {
	return p.Req
}

type PushDataResult struct {
	Success *kitex_gen.PushDataResp
}

var PushDataResult_Success_DEFAULT *kitex_gen.PushDataResp

func (p *PushDataResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *PushDataResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.PushDataResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PushDataResult) GetSuccess() *kitex_gen.PushDataResp {
	if !p.IsSetSuccess() {
		return PushDataResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PushDataResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.PushDataResp)
}

func (p *PushDataResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PushDataResult) GetResult() interface{} {
	return p.Success
}

func pushToConnectionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.PushToConnectionReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.BackbonService).PushToConnection(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *PushToConnectionArgs:
		success, err := handler.(kitex_gen.BackbonService).PushToConnection(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PushToConnectionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newPushToConnectionArgs() interface{} {
	return &PushToConnectionArgs{}
}

func newPushToConnectionResult() interface{} {
	return &PushToConnectionResult{}
}

type PushToConnectionArgs struct {
	Req *kitex_gen.PushToConnectionReq
}

func (p *PushToConnectionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *PushToConnectionArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.PushToConnectionReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PushToConnectionArgs_Req_DEFAULT *kitex_gen.PushToConnectionReq

func (p *PushToConnectionArgs) GetReq() *kitex_gen.PushToConnectionReq {
	if !p.IsSetReq() {
		return PushToConnectionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PushToConnectionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PushToConnectionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type PushToConnectionResult struct {
	Success *kitex_gen.PushToConnectionResp
}

var PushToConnectionResult_Success_DEFAULT *kitex_gen.PushToConnectionResp

func (p *PushToConnectionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *PushToConnectionResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.PushToConnectionResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PushToConnectionResult) GetSuccess() *kitex_gen.PushToConnectionResp {
	if !p.IsSetSuccess() {
		return PushToConnectionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PushToConnectionResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.PushToConnectionResp)
}

func (p *PushToConnectionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PushToConnectionResult) GetResult() interface{} {
	return p.Success
}

func registerServiceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.RegisterServiceReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.BackbonService).RegisterService(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RegisterServiceArgs:
		success, err := handler.(kitex_gen.BackbonService).RegisterService(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RegisterServiceResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRegisterServiceArgs() interface{} {
	return &RegisterServiceArgs{}
}

func newRegisterServiceResult() interface{} {
	return &RegisterServiceResult{}
}

type RegisterServiceArgs struct {
	Req *kitex_gen.RegisterServiceReq
}

func (p *RegisterServiceArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RegisterServiceArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.RegisterServiceReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RegisterServiceArgs_Req_DEFAULT *kitex_gen.RegisterServiceReq

func (p *RegisterServiceArgs) GetReq() *kitex_gen.RegisterServiceReq {
	if !p.IsSetReq() {
		return RegisterServiceArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RegisterServiceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RegisterServiceArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RegisterServiceResult struct {
	Success *kitex_gen.RegisterServiceResp
}

var RegisterServiceResult_Success_DEFAULT *kitex_gen.RegisterServiceResp

func (p *RegisterServiceResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RegisterServiceResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.RegisterServiceResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RegisterServiceResult) GetSuccess() *kitex_gen.RegisterServiceResp {
	if !p.IsSetSuccess() {
		return RegisterServiceResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RegisterServiceResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.RegisterServiceResp)
}

func (p *RegisterServiceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RegisterServiceResult) GetResult() interface{} {
	return p.Success
}

func unregisterServiceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.UnregisterServiceReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.BackbonService).UnregisterService(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnregisterServiceArgs:
		success, err := handler.(kitex_gen.BackbonService).UnregisterService(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnregisterServiceResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnregisterServiceArgs() interface{} {
	return &UnregisterServiceArgs{}
}

func newUnregisterServiceResult() interface{} {
	return &UnregisterServiceResult{}
}

type UnregisterServiceArgs struct {
	Req *kitex_gen.UnregisterServiceReq
}

func (p *UnregisterServiceArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnregisterServiceArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.UnregisterServiceReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnregisterServiceArgs_Req_DEFAULT *kitex_gen.UnregisterServiceReq

func (p *UnregisterServiceArgs) GetReq() *kitex_gen.UnregisterServiceReq {
	if !p.IsSetReq() {
		return UnregisterServiceArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnregisterServiceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnregisterServiceArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnregisterServiceResult struct {
	Success *kitex_gen.UnregisterServiceResp
}

var UnregisterServiceResult_Success_DEFAULT *kitex_gen.UnregisterServiceResp

func (p *UnregisterServiceResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnregisterServiceResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.UnregisterServiceResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnregisterServiceResult) GetSuccess() *kitex_gen.UnregisterServiceResp {
	if !p.IsSetSuccess() {
		return UnregisterServiceResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnregisterServiceResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.UnregisterServiceResp)
}

func (p *UnregisterServiceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnregisterServiceResult) GetResult() interface{} {
	return p.Success
}

func getServiceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.GetServiceReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.BackbonService).GetService(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetServiceArgs:
		success, err := handler.(kitex_gen.BackbonService).GetService(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetServiceResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetServiceArgs() interface{} {
	return &GetServiceArgs{}
}

func newGetServiceResult() interface{} {
	return &GetServiceResult{}
}

type GetServiceArgs struct {
	Req *kitex_gen.GetServiceReq
}

func (p *GetServiceArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetServiceArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GetServiceReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetServiceArgs_Req_DEFAULT *kitex_gen.GetServiceReq

func (p *GetServiceArgs) GetReq() *kitex_gen.GetServiceReq {
	if !p.IsSetReq() {
		return GetServiceArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetServiceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetServiceArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetServiceResult struct {
	Success *kitex_gen.GetServiceResp
}

var GetServiceResult_Success_DEFAULT *kitex_gen.GetServiceResp

func (p *GetServiceResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetServiceResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GetServiceResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetServiceResult) GetSuccess() *kitex_gen.GetServiceResp {
	if !p.IsSetSuccess() {
		return GetServiceResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetServiceResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.GetServiceResp)
}

func (p *GetServiceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetServiceResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CheckUserOnline(ctx context.Context, Req *kitex_gen.CheckUserOnlineReq) (r *kitex_gen.CheckUserOnlineResp, err error) {
	var _args CheckUserOnlineArgs
	_args.Req = Req
	var _result CheckUserOnlineResult
	if err = p.c.Call(ctx, "CheckUserOnline", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PushData(ctx context.Context, Req *kitex_gen.PushDataReq) (r *kitex_gen.PushDataResp, err error) {
	var _args PushDataArgs
	_args.Req = Req
	var _result PushDataResult
	if err = p.c.Call(ctx, "PushData", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PushToConnection(ctx context.Context, Req *kitex_gen.PushToConnectionReq) (r *kitex_gen.PushToConnectionResp, err error) {
	var _args PushToConnectionArgs
	_args.Req = Req
	var _result PushToConnectionResult
	if err = p.c.Call(ctx, "PushToConnection", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RegisterService(ctx context.Context, Req *kitex_gen.RegisterServiceReq) (r *kitex_gen.RegisterServiceResp, err error) {
	var _args RegisterServiceArgs
	_args.Req = Req
	var _result RegisterServiceResult
	if err = p.c.Call(ctx, "RegisterService", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnregisterService(ctx context.Context, Req *kitex_gen.UnregisterServiceReq) (r *kitex_gen.UnregisterServiceResp, err error) {
	var _args UnregisterServiceArgs
	_args.Req = Req
	var _result UnregisterServiceResult
	if err = p.c.Call(ctx, "UnregisterService", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetService(ctx context.Context, Req *kitex_gen.GetServiceReq) (r *kitex_gen.GetServiceResp, err error) {
	var _args GetServiceArgs
	_args.Req = Req
	var _result GetServiceResult
	if err = p.c.Call(ctx, "GetService", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
